import logging
import re
from typing import Optional

import httpx
from selectolax.parser import HTMLParser

from financials.models import FinancialMetrics
from financials.providers.base import BaseProvider

logger = logging.getLogger(__name__)


class InvestirLesEchosProvider(BaseProvider):
    """
    InvestirLesEchos Provider.
    """

    SEARCH_API = "https://lesechosprx.solutions.webfg.ch/mdp-auth/lesechos-api/quotes/_multisearch"
    PREFERRED_MICS = ("XNAS", "XNYS", "ARCX", "XPAR", "XAMS", "XLON")

    def __init__(self, max_retries: int = 3, timeout: int = 15):
        self.max_retries = max_retries
        self.timeout = timeout
        self._dynamic_token: Optional[str] = None

    async def get_financials(self, ticker: str) -> Optional[FinancialMetrics]:
        async with httpx.AsyncClient(timeout=self.timeout, follow_redirects=True) as client:
            search_result = await self._search_result(client, ticker)
            if not search_result:
                return None

            metrics = self._metrics_from_search_result(search_result, ticker)

            try:
                resp = await client.get(search_result["url"], headers={"User-Agent": "Mozilla/5.0"})
                if resp.status_code == 200:
                    page_metrics = self._parse_page(HTMLParser(resp.text), ticker)
                    for field, value in page_metrics.model_dump(exclude_none=True).items():
                        setattr(metrics, field, value)
                else:
                    logger.warning(
                        f"InvestirLesEchos page fetch status {resp.status_code} for {search_result['url']}"
                    )
            except Exception as e:
                logger.error(f"InvestirLesEchos fetch error: {e}")
            return metrics

    async def _get_dynamic_token(self, client: httpx.AsyncClient) -> Optional[str]:
        if self._dynamic_token:
            return self._dynamic_token

        try:
            # We fetch a page from the website to extract the dynamic token generated by Next.js
            headers = {
                "User-Agent": "Mozilla/5.0 (Windows NT 10.0; Win64; x64)",
                "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8",
            }
            resp = await client.get("https://investir.lesechos.fr/recherche", headers=headers)
            if resp.status_code == 200:
                import re

                tokens = re.findall(r"eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+", resp.text)
                if tokens:
                    self._dynamic_token = f"Bearer {tokens[0]}"
                    return self._dynamic_token
        except Exception as e:
            logger.warning(f"InvestirLesEchos token extraction error: {e}")

        return None

    async def _search_result(self, client: httpx.AsyncClient, query: str) -> Optional[dict]:
        token = await self._get_dynamic_token(client)
        if not token:
            return None

        params = {"fields": "DISPLAY_NAME,M_SYMB,MIC,ISIN", "q": query, "size": 10, "t": "EQU,ETF"}
        headers = {
            "Authorization": token,
            "User-Agent": "Mozilla/5.0",
            "Accept": "application/json, text/plain, */*",
            "Origin": "https://investir.lesechos.fr",
            "Referer": "https://investir.lesechos.fr/",
        }
        try:
            resp = await client.get(self.SEARCH_API, params=params, headers=headers)
            if resp.status_code == 200:
                data = resp.json()
                hit = self._select_hit(data, query)
                if hit:
                    return self._search_result_from_hit(hit)
            else:
                logger.warning(f"InvestirLesEchos search status {resp.status_code} for {query}")
        except Exception as e:
            logger.warning(f"InvestirLesEchos search error for {query}: {e}")
        return None

    async def _search_url(self, client: httpx.AsyncClient, query: str) -> Optional[str]:
        search_result = await self._search_result(client, query)
        return search_result["url"] if search_result else None

    @staticmethod
    def _field_value(hit: dict, field: str) -> str:
        value = (hit.get("fields") or {}).get(field, {})
        if isinstance(value, dict):
            return (value.get("v") or "").strip()
        return str(value or "").strip()

    @classmethod
    def _select_hit(cls, data: dict, query: str) -> Optional[dict]:
        hits = [hit for category in data.get("categories", []) for hit in category.get("hits", [])]
        valid_hits = [
            hit
            for hit in hits
            if all(
                cls._field_value(hit, field) for field in ("DISPLAY_NAME", "M_SYMB", "ISIN", "MIC")
            )
        ]
        if not valid_hits:
            return None

        query_upper = (query or "").strip().upper()

        def rank(hit):
            symbol = cls._field_value(hit, "M_SYMB").upper()
            isin = cls._field_value(hit, "ISIN").upper()
            mic = cls._field_value(hit, "MIC").upper()
            return (
                symbol != query_upper and isin != query_upper,
                mic not in cls.PREFERRED_MICS,
                cls.PREFERRED_MICS.index(mic)
                if mic in cls.PREFERRED_MICS
                else len(cls.PREFERRED_MICS),
                symbol,
            )

        return sorted(valid_hits, key=rank)[0]

    @classmethod
    def _search_result_from_hit(cls, hit: dict) -> Optional[dict]:
        display_name = cls._field_value(hit, "DISPLAY_NAME")
        symbol = cls._field_value(hit, "M_SYMB")
        isin = cls._field_value(hit, "ISIN")
        mic = cls._field_value(hit, "MIC")
        if not all((display_name, symbol, isin, mic)):
            return None

        display_slug = re.sub(r"[^a-z0-9]+", "-", display_name.lower()).strip("-")
        symbol_slug = re.sub(r"[^a-z0-9]+", "-", symbol.lower()).strip("-")
        url = f"https://investir.lesechos.fr/cours/actions/{display_slug}-{symbol_slug}-{isin.lower()}-{mic.lower()}"

        return {
            "url": url,
            "name": display_name,
            "ticker": symbol.upper(),
            "isin": isin.upper(),
            "mic": mic.upper(),
        }

    @staticmethod
    def _metrics_from_search_result(search_result: dict, ticker_input: str) -> FinancialMetrics:
        return FinancialMetrics(
            name=search_result.get("name"),
            ticker=search_result.get("ticker") or ticker_input,
            isin=search_result.get("isin"),
            provider_url=search_result.get("url"),
        )

    def _parse_page(self, parser: HTMLParser, ticker_input: str) -> FinancialMetrics:
        metrics = FinancialMetrics(ticker=ticker_input)

        # Name
        h1 = parser.css_first("h1")
        if h1:
            metrics.name = h1.text(strip=True)

        # Price
        price_node = parser.css_first("span.typography-secondary-2xl-regular")
        if price_node:
            metrics.price = self._clean_number(price_node.text(strip=True))

        # Variation
        var_node = parser.css_first("span.typography-secondary-2xl-bold")
        if var_node:
            metrics.change_percent = self._clean_number(var_node.text(strip=True))

        # ISIN and Ticker from Canonical URL or Meta
        canonical = parser.css_first('link[rel="canonical"]')
        if canonical:
            import re

            url = canonical.attributes.get("href", "")
            # URL format: .../apple-aapl-us0378331005-xnas
            match = re.search(r"-([a-z0-9]+)-([a-z0-9]{12})-[a-z0-9]+$", url, re.IGNORECASE)
            if match:
                metrics.ticker = match.group(1).upper()
                metrics.isin = match.group(2).upper()

        return metrics

    def _clean_number(self, text: str) -> Optional[float]:
        try:
            # Nettoyage format français "293,320 $" -> "293.32"
            clean = (
                text.replace(" ", "")
                .replace(",", ".")
                .replace("%", "")
                .replace("$", "")
                .replace("€", "")
                .replace("+", "")
                .strip()
            )
            return float(clean)
        except (ValueError, TypeError):
            return None
